In [54]:
import pandas as pd

path ="../datasets/Iris.csv"
df = pd.read_csv(path)

df.columns

Index(['Id', 'SepalLengthCm', 'SepalWidthCm', 'PetalLengthCm', 'PetalWidthCm',
       'Species'],
      dtype='object')

In [55]:
df["Species"].unique().tolist()

['Iris-setosa', 'Iris-versicolor', 'Iris-virginica']

###  Label Binarizer

In [56]:
from sklearn.preprocessing import LabelBinarizer

# creating a copy of the
# original data frame
df1 = df.copy().drop(columns=['Id'])

# creating an object 
# of the Label Binarizer
label_binarizer = LabelBinarizer()

# fitting the column 
# Species to LabelBinarizer
label_binarizer_output = label_binarizer.fit_transform( df1['Species'] )

# creating a data frame from the object
result_df = pd.DataFrame(label_binarizer_output,
                         columns = label_binarizer.classes_)

df1 = pd.concat([df1, result_df], axis = 1).drop(columns=['Species'])
display(df1)

,SepalLengthCm,SepalWidthCm,PetalLengthCm,PetalWidthCm,Iris-setosa,Iris-versicolor,Iris-virginica
0,5.1,3.5,1.4,0.2,1,0,0
1,4.9,3.0,1.4,0.2,1,0,0
2,4.7,3.2,1.3,0.2,1,0,0
3,4.6,3.1,1.5,0.2,1,0,0
4,5.0,3.6,1.4,0.2,1,0,0
...,...,...,...,...,...,...,...
145,6.7,3.0,5.2,2.3,0,0,1
146,6.3,2.5,5.0,1.9,0,0,1
147,6.5,3.0,5.2,2.0,0,0,1
148,6.2,3.4,5.4,2.3,0,0,1
149,5.9,3.0,5.1,1.8,0,0,1

In [57]:
df1.columns.tolist()

['SepalLengthCm',
 'SepalWidthCm',
 'PetalLengthCm',
 'PetalWidthCm',
 'Iris-setosa',
 'Iris-versicolor',
 'Iris-virginica']

### Binary Encoding

In [59]:
%pip install category_encoders
import category_encoders as cat_encoder

# creating a copy of the
# original data frame
df2 = df.copy().drop(columns=['Id'])

# creating an object BinaryEncoder
encoder = cat_encoder.BinaryEncoder(cols = ['Species'])

# fitting the columns to a data frame
result_df = encoder.fit_transform(df2['Species'])

df2 = pd.concat([df2, result_df], axis = 1).drop(columns=['Species'])
display(df2)

Requirement already satisfied: category_encoders in c:\users\han\anaconda3\lib\site-packages (2.8.1)
Requirement already satisfied: numpy>=1.14.0 in c:\users\han\anaconda3\lib\site-packages (from category_encoders) (1.26.4)
Requirement already satisfied: pandas>=1.0.5 in c:\users\han\anaconda3\lib\site-packages (from category_encoders) (2.2.3)
Requirement already satisfied: patsy>=0.5.1 in c:\users\han\anaconda3\lib\site-packages (from category_encoders) (0.5.6)
Requirement already satisfied: scikit-learn>=1.6.0 in c:\users\han\anaconda3\lib\site-packages (from category_encoders) (1.6.1)
Requirement already satisfied: scipy>=1.0.0 in c:\users\han\anaconda3\lib\site-packages (from category_encoders) (1.13.1)
Requirement already satisfied: statsmodels>=0.9.0 in c:\users\han\anaconda3\lib\site-packages (from category_encoders) (0.14.4)
Requirement already satisfied: six in c:\users\han\anaconda3\lib\site-packages (from patsy>=0.5.1->category_encoders) (1.16.0)
Requirement already satisfied: joblib>=1.2.0 in c:\users\han\anaconda3\lib\site-packages (from scikit-learn>=1.6.0->category_encoders) (1.4.2)
Requirement already satisfied: threadpoolctl>=3.1.0 in c:\users\han\anaconda3\lib\site-packages (from scikit-learn>=1.6.0->category_encoders) (3.5.0)
Requirement already satisfied: packaging>=21.3 in c:\users\han\anaconda3\lib\site-packages (from statsmodels>=0.9.0->category_encoders) (23.2)
Note: you may need to restart the kernel to use updated packages.

WARNING: Ignoring invalid distribution ~yspark (c:\Users\Han\anaconda3\Lib\site-packages)
WARNING: Ignoring invalid distribution ~yspark (c:\Users\Han\anaconda3\Lib\site-packages)
WARNING: Ignoring invalid distribution ~yspark (c:\Users\Han\anaconda3\Lib\site-packages)

,SepalLengthCm,SepalWidthCm,PetalLengthCm,PetalWidthCm,Species_0,Species_1
0,5.1,3.5,1.4,0.2,0,1
1,4.9,3.0,1.4,0.2,0,1
2,4.7,3.2,1.3,0.2,0,1
3,4.6,3.1,1.5,0.2,0,1
4,5.0,3.6,1.4,0.2,0,1
...,...,...,...,...,...,...
145,6.7,3.0,5.2,2.3,1,1
146,6.3,2.5,5.0,1.9,1,1
147,6.5,3.0,5.2,2.0,1,1
148,6.2,3.4,5.4,2.3,1,1
149,5.9,3.0,5.1,1.8,1,1

In [60]:
df2.columns.tolist()

['SepalLengthCm',
 'SepalWidthCm',
 'PetalLengthCm',
 'PetalWidthCm',
 'Species_0',
 'Species_1']

### One Hot Encoding

In [62]:
# creating a copy of the
# original data frame
df3 = df.copy().drop(columns=['Id'])

df3 = pd.get_dummies(df3,columns = ['Species'])

display(df3)

,SepalLengthCm,SepalWidthCm,PetalLengthCm,PetalWidthCm,Species_Iris-setosa,Species_Iris-versicolor,Species_Iris-virginica
0,5.1,3.5,1.4,0.2,True,False,False
1,4.9,3.0,1.4,0.2,True,False,False
2,4.7,3.2,1.3,0.2,True,False,False
3,4.6,3.1,1.5,0.2,True,False,False
4,5.0,3.6,1.4,0.2,True,False,False
...,...,...,...,...,...,...,...
145,6.7,3.0,5.2,2.3,False,False,True
146,6.3,2.5,5.0,1.9,False,False,True
147,6.5,3.0,5.2,2.0,False,False,True
148,6.2,3.4,5.4,2.3,False,False,True
149,5.9,3.0,5.1,1.8,False,False,True

In [63]:
df3.columns.tolist()

['SepalLengthCm',
 'SepalWidthCm',
 'PetalLengthCm',
 'PetalWidthCm',
 'Species_Iris-setosa',
 'Species_Iris-versicolor',
 'Species_Iris-virginica']

### Label Encoding

In [64]:
# creating a copy of the
# original data frame
df4 = df.copy().drop(columns=['Id'])

# Convert target variable (Species) as category
df4.Species = df4.Species.astype('category')

df4["Species"] = df4.Species.cat.codes
display(df4)

     SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm  Species
0              5.1           3.5            1.4           0.2        0
1              4.9           3.0            1.4           0.2        0
2              4.7           3.2            1.3           0.2        0
3              4.6           3.1            1.5           0.2        0
4              5.0           3.6            1.4           0.2        0
..             ...           ...            ...           ...      ...
145            6.7           3.0            5.2           2.3        2
146            6.3           2.5            5.0           1.9        2
147            6.5           3.0            5.2           2.0        2
148            6.2           3.4            5.4           2.3        2
149            5.9           3.0            5.1           1.8        2

[150 rows x 5 columns]

In [66]:
df4.columns.tolist()

['SepalLengthCm', 'SepalWidthCm', 'PetalLengthCm', 'PetalWidthCm', 'Species']

In [67]:
from sklearn.datasets import load_iris
iris = load_iris()

import numpy as np
df5 = pd.DataFrame(data=np.column_stack((iris.data, iris.target)),
				  columns=iris.feature_names + ['target'])
display(df5)

,sepal length (cm),sepal width (cm),petal length (cm),petal width (cm),target
0,5.1,3.5,1.4,0.2,0.0
1,4.9,3.0,1.4,0.2,0.0
2,4.7,3.2,1.3,0.2,0.0
3,4.6,3.1,1.5,0.2,0.0
4,5.0,3.6,1.4,0.2,0.0
...,...,...,...,...,...
145,6.7,3.0,5.2,2.3,2.0
146,6.3,2.5,5.0,1.9,2.0
147,6.5,3.0,5.2,2.0,2.0
148,6.2,3.4,5.4,2.3,2.0
149,5.9,3.0,5.1,1.8,2.0

In [53]:
df5.columns.tolist()

['sepal length (cm)',
 'sepal width (cm)',
 'petal length (cm)',
 'petal width (cm)',
 'target']